name: thesis
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - ipykernel
  - numpy
  - scipy
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - scikit-image
  - pip
  - pip:
      - nibabel
      - albumentations
      - opencv-python
      - tqdm
      - gdown
      - matplotlib
